### ISSUE TITLE
Error: CONFIG_PATH environment variable is missing

### ISSUE THREAD

**Issue by Vylesh** [VueTorrent/vuetorrent-backend#47]
Idk What am I Doing wrong but When I Run Docker Image I getting this error which wroten on title

Detailed one is in below
2024-09-20 22:16:59 
2024-09-20 22:16:59 Node.js v21.7.3
2024-09-20 22:20:10 file:///app/src/utils.js:4
2024-09-20 22:20:10       throw new Error(`${ key } environment variable is missing`)
2024-09-20 22:20:10             ^
2024-09-20 22:20:10 
2024-09-20 22:20:10 Error: CONFIG_PATH environment variable is missing
2024-09-20 22:20:10     at assert_env (file:///app/src/utils.js:4:13)
2024-09-20 22:20:10     at file:///app/src/index.js:13:1
2024-09-20 22:20:10     at ModuleJob.run (node:internal/modules/esm/module_job:222:25)
2024-09-20 22:20:10     at async ModuleLoader.import (node:internal/modules/esm/loader:323:24)
2024-09-20 22:20:10     at async loadESM (node:internal/process/esm_loader:28:7)
2024-09-20 22:20:10     at async handleMainPromise (node:internal/modules/run_main:120:12)
2024-09-20 22:20:10 
2024-09-20 22:20:10 Node.js v21.7.3

**Comment by Larsluph** [comment]
As the error states, you're missing an environment variable

```yml
    environment:
      - CONFIG_PATH=/config
```

You can specify it with `-e CONFIG_PATH=/config` if using docker run.
